// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "projectId": "studio-8782812450-3690f",
  "appId": "1:707979652934:web:1e5077af89b68708c6ff47",
  "apiKey": "AIzaSyCZM0RwCRs7QRHN4kFr-QyLzALq-opaNBI",
  "authDomain": "studio-8782812450-3690f.firebaseapp.com",
  "storageBucket": "studio-8782812450-3690f.appspot.com",
  "messagingSenderId": "707979652934",
};
